# Usar Python 3.11 slim
FROM python:3.11-slim

WORKDIR /app

# Evitar problemas de locales UTF-8
ENV LANG=C.UTF-8

# Copiar requirements.txt
COPY requirements.txt .

# Instalar dependencias del sistema y Python
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        g++ \
        libpq-dev \
        libffi-dev \
        build-essential \
        curl \
        ca-certificates \
        make \
        git \
        libssl-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get purge -y --auto-remove gcc g++ build-essential libffi-dev make && \
    rm -rf /var/lib/apt/lists/*

# Copiar el script
COPY app.py .

# Crear carpeta de datos si no existe
RUN mkdir -p /data

# Comando por defecto
CMD ["python", "app.py"]
