FROM flink:1.19-scala_2.12

# Instalar dependencias de Python
USER root
RUN apt-get update && apt-get install -y python3 python3-pip
COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt

COPY Reprocessor_Flink.py /app/Reprocessor_Flink.py
WORKDIR /app

USER flink
CMD ["python3", "Reprocessor_Flink.py"]
