FROM apache/flink:1.19-scala_2.12

USER root
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

# Instalar PyFlink
RUN pip install --no-cache-dir apache-flink==1.19.0

COPY Reprocessor_Flink.py /app/Reprocessor_Flink.py
WORKDIR /app

USER flink
CMD ["python3", "Reprocessor_Flink.py"]
